/**
 * Apify Leads Finder (`code_crafter/leads-finder`) `contact_location` enum values.
 * @see https://apify.com/code_crafter/leads-finder/input-schema
 */

/** All allowed `contact_location` values (lowercase). */
export const APIFY_CONTACT_LOCATIONS = new Set([
  'united states',
  'germany',
  'india',
  'united kingdom',
  'russia',
  'france',
  'china',
  'canada',
  'netherlands',
  'mexico',
  'belgium',
  'japan',
  'brazil',
  'australia',
  'poland',
  'thailand',
  'sweden',
  'portugal',
  'spain',
  'czech republic',
  'taiwan',
  'south africa',
  'colombia',
  'italy',
  'vietnam',
  'nigeria',
  'singapore',
  'hong kong',
  'ireland',
  'israel',
  'switzerland',
  'turkey',
  'romania',
  'south korea',
  'indonesia',
  'united arab emirates',
  'saudi arabia',
  'austria',
  'philippines',
  'peru',
  'malaysia',
  'argentina',
  'ukraine',
  'ghana',
  'denmark',
  'norway',
  'finland',
  'puerto rico',
  'qatar',
  'macau',
  'new zealand',
  'hungary',
  'luxembourg',
  'kuwait',
  'egypt',
  'slovakia',
  'greece',
  'kenya',
  'bulgaria',
  'costa rica',
  'chile',
  'venezuela',
  'afghanistan',
  'bangladesh',
  'malta',
  'guatemala',
  'pakistan',
  'lithuania',
  'panama',
  'morocco',
  'republic of indonesia',
  'uruguay',
  'serbia',
  'bolivia',
  'angola',
  'dominican republic',
  'ecuador',
  'oman',
  'jamaica',
  'zambia',
  'lebanon',
  'tanzania',
  'jordan',
  'algeria',
  'gibraltar',
  'paraguay',
  'cambodia',
  'uganda',
  'mozambique',
  'ethiopia',
  'belarus',
  'republic of the union of myanmar',
  'croatia',
  'jersey',
  'iraq',
  'isle of man',
  'el salvador',
  'estonia',
  'latvia',
  "côte d'ivoire",
  'tunisia',
  'sierra leone',
  'senegal',
  'sri lanka',
  'cyprus',
  'kazakhstan',
  'guernsey',
  'bermuda',
  'mali',
  'honduras',
  'bahrain',
  'slovenia',
  'papua new guinea',
  'iceland',
  'mauritius',
  'iran',
  'niger',
  'rwanda',
  'moldova',
  'democratic republic of the congo',
  'liechtenstein',
  'fiji',
  'kyrgyzstan',
  'azerbaijan',
  'madagascar',
  'trinidad and tobago',
  'lesotho',
  'nicaragua',
  'cameroon',
  'barbados',
  'armenia',
  'haiti',
  'maldives',
  'guam',
  'laos',
  'nepal',
  'brunei',
  'reunion',
  'macedonia (fyrom)',
  'swaziland',
  'liberia',
  'uzbekistan',
  'sudan',
  'anguilla',
  'cuba',
  'cayman islands',
  'seychelles',
  'saint kitts and nevis',
  'suriname',
  'bosnia and herzegovina',
  'malawi',
  'the bahamas',
  'botswana',
  'syria',
  'burundi',
  'guadeloupe',
  'namibia',
  'burkina faso',
  'somalia',
  'greenland',
  'equatorial guinea',
  'chad',
  'monaco',
  'republic of the congo',
  'u.s. virgin islands',
  'mayotte',
  'french polynesia',
  'french guiana',
  'andorra',
  'new caledonia',
  'central african republic',
  'myanmar (burma)',
  'belize',
  'aland islands',
  'solomon islands',
  'kosovo',
  'gabon',
  'benin',
  'bonaire, sint eustatius and saba',
  'martinique',
  'tonga',
  'south sudan',
  'cook islands',
  'georgia',
  'mauritania',
  'turkmenistan',
  'libya',
  'falkland islands (islas malvinas)',
  'bhutan',
  'tajikistan',
  'northern mariana islands',
  'western sahara',
  'guyana',
  'dominica',
  'vanuatu',
  'kiribati',
  'togo',
  'nauru',
  'samoa',
  'mongolia',
  'myanmar',
  'yemen',
  'albania',
  'montenegro',
  'california, us',
  'texas, us',
  'england, united kingdom',
  'new york, us',
  'florida, us',
  'illinois, us',
  'moscow, russia',
  'bavaria, germany',
  'pennsylvania, us',
  'virginia, us',
  'ohio, us',
  'massachusetts, us',
  'baden-württemberg, germany',
  'north rhine-westphalia, germany',
  'georgia, us',
  'michigan, us',
  'north carolina, us',
  'maryland, us',
  'berlin, germany',
  'new jersey, us',
  'bangkok, thailand',
  'île-de-france, france',
  'maharashtra, india',
  'washington, us',
  'ontario, canada',
  'beijing, china',
  'colorado, us',
  'minnesota, us',
  'karnataka, india',
  'hamburg, germany',
  'indiana, us',
  'shanghai, china',
  'lisbon, portugal',
  'flanders, belgium',
  'arizona, us',
  'ciudad de méxico, mexico',
  'wisconsin, us',
  'tennessee, us',
  'missouri, us',
  'saint petersburg, russia',
  'hesse, germany',
  'tamil nadu, india',
  'oregon, us',
  'lower saxony, germany',
  'south carolina, us',
  'connecticut, us',
  'delhi, india',
  'north holland, netherlands',
  'kentucky, us',
  'new south wales, australia',
  'district of columbia, us',
  'telangana, india',
  'iowa, us',
  'guangdong, china',
  'nevada, us',
  'alabama, us',
  'louisiana, us',
  'state of são paulo, brazil',
  'british columbia, canada',
  'utah, us',
  'kansas, us',
  'saxony, germany',
  'lagos, nigeria',
  'nebraska, us',
  'oklahoma, us',
  'overijssel, netherlands',
])

const COUNTRY_ALIASES: Record<string, string> = {
  us: 'united states',
  usa: 'united states',
  'u.s.': 'united states',
  'u.s.a.': 'united states',
  'united states of america': 'united states',
  america: 'united states',
  uk: 'united kingdom',
  'great britain': 'united kingdom',
  britain: 'united kingdom',
  uae: 'united arab emirates',
}

/** US state / DC → Apify regional value (`state, us`). */
const US_STATE_TO_APIFY: Record<string, string> = {
  al: 'alabama, us',
  alabama: 'alabama, us',
  ak: 'alaska, us',
  alaska: 'alaska, us',
  az: 'arizona, us',
  arizona: 'arizona, us',
  ar: 'arkansas, us',
  arkansas: 'arkansas, us',
  ca: 'california, us',
  california: 'california, us',
  co: 'colorado, us',
  colorado: 'colorado, us',
  ct: 'connecticut, us',
  connecticut: 'connecticut, us',
  dc: 'district of columbia, us',
  'district of columbia': 'district of columbia, us',
  de: 'delaware, us',
  delaware: 'delaware, us',
  fl: 'florida, us',
  florida: 'florida, us',
  ga: 'georgia, us',
  hi: 'hawaii, us',
  hawaii: 'hawaii, us',
  id: 'idaho, us',
  idaho: 'idaho, us',
  il: 'illinois, us',
  illinois: 'illinois, us',
  in: 'indiana, us',
  indiana: 'indiana, us',
  ia: 'iowa, us',
  iowa: 'iowa, us',
  ks: 'kansas, us',
  kansas: 'kansas, us',
  ky: 'kentucky, us',
  kentucky: 'kentucky, us',
  la: 'louisiana, us',
  louisiana: 'louisiana, us',
  me: 'maine, us',
  maine: 'maine, us',
  md: 'maryland, us',
  maryland: 'maryland, us',
  ma: 'massachusetts, us',
  massachusetts: 'massachusetts, us',
  mi: 'michigan, us',
  michigan: 'michigan, us',
  mn: 'minnesota, us',
  minnesota: 'minnesota, us',
  ms: 'mississippi, us',
  mississippi: 'mississippi, us',
  mo: 'missouri, us',
  missouri: 'missouri, us',
  mt: 'montana, us',
  montana: 'montana, us',
  ne: 'nebraska, us',
  nebraska: 'nebraska, us',
  nv: 'nevada, us',
  nevada: 'nevada, us',
  nh: 'new hampshire, us',
  'new hampshire': 'new hampshire, us',
  nj: 'new jersey, us',
  'new jersey': 'new jersey, us',
  nm: 'new mexico, us',
  'new mexico': 'new mexico, us',
  ny: 'new york, us',
  'new york': 'new york, us',
  nc: 'north carolina, us',
  'north carolina': 'north carolina, us',
  nd: 'north dakota, us',
  'north dakota': 'north dakota, us',
  oh: 'ohio, us',
  ohio: 'ohio, us',
  ok: 'oklahoma, us',
  oklahoma: 'oklahoma, us',
  or: 'oregon, us',
  oregon: 'oregon, us',
  pa: 'pennsylvania, us',
  pennsylvania: 'pennsylvania, us',
  ri: 'rhode island, us',
  'rhode island': 'rhode island, us',
  sc: 'south carolina, us',
  'south carolina': 'south carolina, us',
  sd: 'south dakota, us',
  'south dakota': 'south dakota, us',
  tn: 'tennessee, us',
  tennessee: 'tennessee, us',
  tx: 'texas, us',
  texas: 'texas, us',
  ut: 'utah, us',
  utah: 'utah, us',
  vt: 'vermont, us',
  vermont: 'vermont, us',
  va: 'virginia, us',
  virginia: 'virginia, us',
  wa: 'washington, us',
  washington: 'washington, us',
  wv: 'west virginia, us',
  'west virginia': 'west virginia, us',
  wi: 'wisconsin, us',
  wisconsin: 'wisconsin, us',
  wy: 'wyoming, us',
  wyoming: 'wyoming, us',
}

const DEFAULT_LOCATION = 'united states'

function isAllowedLocation(value: string): boolean {
  return APIFY_CONTACT_LOCATIONS.has(value)
}

function resolveUsStateToken(token: string): string | null {
  const mapped = US_STATE_TO_APIFY[token.trim().toLowerCase()]
  if (!mapped) return null
  return isAllowedLocation(mapped) ? mapped : null
}

/** Parse "Phoenix AZ", "Dallas, TX", "California", "AZ" → Apify location. */
function resolveUsLocation(input: string): string | null {
  const trimmed = input.trim().toLowerCase()
  if (!trimmed) return null

  const directState = resolveUsStateToken(trimmed)
  if (directState) return directState

  const commaParts = trimmed.split(',').map((part) => part.trim()).filter(Boolean)
  if (commaParts.length >= 2) {
    const stateToken = commaParts[commaParts.length - 1]!
    const fromState = resolveUsStateToken(stateToken)
    if (fromState) return fromState
  }

  const words = trimmed.split(/\s+/).filter(Boolean)
  if (words.length >= 2) {
    const lastWord = words[words.length - 1]!
    if (/^[a-z]{2}$/.test(lastWord)) {
      const fromAbbrev = resolveUsStateToken(lastWord)
      if (fromAbbrev) return fromAbbrev
    }
  }

  if (trimmed.endsWith(', us') || trimmed.endsWith(', usa')) {
    const region = trimmed.replace(/,\s*(us|usa)$/, '').trim()
    const candidate = `${region}, us`
    if (isAllowedLocation(candidate)) return candidate
  }

  return null
}

/** Map one UI location string to a valid Apify `contact_location` value, or null. */
export function normalizeApifyLocation(raw: string): string | null {
  const key = raw.trim().toLowerCase()
  if (!key) return null

  const aliased = COUNTRY_ALIASES[key] ?? key
  if (isAllowedLocation(aliased)) return aliased

  const usResolved = resolveUsLocation(key)
  if (usResolved) return usResolved

  return null
}

/**
 * Normalize UI location strings to Apify `contact_location` enum values.
 * Invalid entries are dropped; falls back to `united states` when nothing resolves.
 */
export function normalizeApifyLocations(locations: string[] | undefined): string[] {
  if (!locations?.length) return [DEFAULT_LOCATION]

  const resolved = locations
    .map((loc) => normalizeApifyLocation(loc))
    .filter((loc): loc is string => loc !== null)

  if (resolved.length === 0) return [DEFAULT_LOCATION]
  return [...new Set(resolved)]
}
